#!/usr/bin/env python3
"""Fetch and parse FeatureScript ErrorStringEnum values into a JSON mapping.

Source: javawizard/onshape-std-library-mirror (MIT-licensed mirror of the
Onshape FeatureScript standard library).

Usage:
    python scripts/generate-error-enums.py           # regenerate the JSON file
    python scripts/generate-error-enums.py --check    # verify committed file is up to date
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.request import urlopen

MIRROR_URL = (
    "https://raw.githubusercontent.com/javawizard/onshape-std-library-mirror"
    "/without-versions/errorstringenum.gen.fs"
)

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "crates"
    / "onshape-mcp-core"
    / "error-enums.json"
)

# Matches: optional /* comment */ on the preceding line, then ENUM_NAME followed
# by a comma or end-of-enum.  We skip the file header by only matching inside
# the enum body (after the opening brace).
_ENTRY_RE = re.compile(
    r"(?:/\*\s*(.*?)\s*\*/\s*\n)?\s*([A-Z][A-Z0-9_]*)\s*[,}]",
    re.DOTALL,
)


def fetch_source() -> str:
    with urlopen(MIRROR_URL, timeout=30) as resp:  # noqa: S310 — trusted URL
        return resp.read().decode("utf-8")


def parse_enums(source: str) -> dict[str, str]:
    # Isolate the enum body (between first { and last })
    brace_start = source.index("{")
    brace_end = source.rindex("}")
    body = source[brace_start + 1 : brace_end]

    mapping: dict[str, str] = {}
    for match in _ENTRY_RE.finditer(body):
        comment, name = match.group(1), match.group(2)
        if comment:
            # Normalise internal whitespace (multi-line comments)
            comment = " ".join(comment.split())
            mapping[name] = comment
    return mapping


def build_output(mapping: dict[str, str]) -> str:
    output = {
        "_meta": {
            "source": MIRROR_URL,
            "license": "MIT",
            "copyright": "Copyright (c) 2013-Present PTC Inc.",
            "description": (
                "FeatureScript ErrorStringEnum to human-readable message mapping. "
                "Generated by scripts/generate-error-enums.py — do not edit by hand."
            ),
        },
        "enums": mapping,
    }
    return json.dumps(output, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    check_mode = "--check" in sys.argv

    source = fetch_source()
    mapping = parse_enums(source)

    if not mapping:
        print(
            "ERROR: parsed zero enum entries — source format may have changed",
            file=sys.stderr,
        )
        sys.exit(1)

    expected = build_output(mapping)

    if check_mode:
        if not OUTPUT_PATH.exists():
            print(f"FAIL: {OUTPUT_PATH} does not exist", file=sys.stderr)
            sys.exit(1)
        committed = OUTPUT_PATH.read_text(encoding="utf-8")
        if committed == expected:
            print(f"OK: {OUTPUT_PATH} is up to date ({len(mapping)} enums)")
        else:
            print(
                f"FAIL: {OUTPUT_PATH} is out of date. "
                f"Run 'python scripts/generate-error-enums.py' to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
    else:
        OUTPUT_PATH.write_text(expected, encoding="utf-8")
        print(f"Wrote {OUTPUT_PATH} ({len(mapping)} enums)")


if __name__ == "__main__":
    main()
