#!/usr/bin/env python3
"""Generate FeatureScript error messages and safe Onshape error-code values.

Messages come from javawizard/onshape-std-library-mirror (MIT-licensed mirror
of the Onshape FeatureScript standard library). The complete safe-code allowlist
also includes GBTErrorStringEnum from the bundled Onshape OpenAPI specification.

Usage:
    python scripts/generate-error-enums.py           # regenerate the JSON file
    python scripts/generate-error-enums.py --check    # verify committed file is up to date
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from urllib.request import urlopen

MIRROR_COMMIT = "a2a7b13ea823f144b20d27198043aea35a64d928"
MIRROR_SOURCE_SHA256 = "5ccb8495cc940524ca7fed65e91c1d406e20a89ba7ea6fccf6677fb344a66dbb"
EXPECTED_MESSAGE_COUNT = 1_723
EXPECTED_SAFE_CODE_COUNT = 1_779
MIRROR_URL = (
    "https://raw.githubusercontent.com/javawizard/onshape-std-library-mirror"
    f"/{MIRROR_COMMIT}/errorstringenum.gen.fs"
)

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "crates"
    / "onshape-mcp-core"
    / "error-enums.json"
)
OPENAPI_PATH = (
    Path(__file__).resolve().parent.parent
    / "crates"
    / "onshape-mcp-io"
    / "onshape-openapi.json"
)

# Matches: optional /* comment */ on the preceding line, then ENUM_NAME followed
# by a comma or end-of-enum.  We skip the file header by only matching inside
# the enum body (after the opening brace).
_ENTRY_RE = re.compile(
    r"(?:/\*\s*(.*?)\s*\*/\s*\n)?\s*([A-Z][A-Z0-9_]*)\s*[,}]",
    re.DOTALL,
)


def fetch_source() -> str:
    with urlopen(MIRROR_URL, timeout=30) as resp:  # noqa: S310 — trusted URL
        content = resp.read()
    digest = hashlib.sha256(content).hexdigest()
    if digest != MIRROR_SOURCE_SHA256:
        raise ValueError(
            f"pinned FeatureScript source SHA-256 changed: {digest}; "
            f"expected {MIRROR_SOURCE_SHA256}"
        )
    return content.decode("utf-8")


def parse_enums(source: str) -> dict[str, str]:
    # Isolate the enum body (between first { and last })
    brace_start = source.index("{")
    brace_end = source.rindex("}")
    body = source[brace_start + 1 : brace_end]

    mapping: dict[str, str] = {}
    for match in _ENTRY_RE.finditer(body):
        comment, name = match.group(1), match.group(2)
        if comment:
            # Normalise internal whitespace (multi-line comments)
            comment = " ".join(comment.split())
            mapping[name] = comment
    return mapping


def load_openapi_codes() -> set[str]:
    spec = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    codes: set[str] = set()
    for schema_name in ("GBTErrorStringEnum", "BTAppElementErrorCode"):
        values = spec["components"]["schemas"][schema_name]["enum"]
        if not isinstance(values, list) or not values or not all(
            isinstance(value, str) and value for value in values
        ):
            raise ValueError(f"{schema_name} must be a nonempty string enum")
        if len(values) != len(set(values)):
            raise ValueError(f"{schema_name} contains duplicate values")
        codes.update(values)
    return codes


def build_output(mapping: dict[str, str], safe_codes: set[str]) -> str:
    output = {
        "_meta": {
            "source": MIRROR_URL,
            "openapi_schemas": ["GBTErrorStringEnum", "BTAppElementErrorCode"],
            "license": "MIT",
            "copyright": "Copyright (c) 2013-Present PTC Inc.",
            "description": (
                "FeatureScript ErrorStringEnum messages and the versioned safe-code "
                "allowlist from FeatureScript plus bundled OpenAPI error enums. "
                "Generated by scripts/generate-error-enums.py — do not edit by hand."
            ),
        },
        "enums": mapping,
        "safe_codes": sorted(safe_codes),
    }
    return json.dumps(output, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--check", action="store_true", help="verify generated output")
    args = parser.parse_args(argv)

    source = fetch_source()
    mapping = parse_enums(source)
    openapi_codes = load_openapi_codes()

    safe_codes = set(mapping) | openapi_codes
    if len(mapping) != EXPECTED_MESSAGE_COUNT:
        raise ValueError(
            f"expected {EXPECTED_MESSAGE_COUNT} message mappings, found {len(mapping)}; "
            "review the pinned source and update the expected count intentionally"
        )
    if len(safe_codes) != EXPECTED_SAFE_CODE_COUNT:
        raise ValueError(
            f"expected {EXPECTED_SAFE_CODE_COUNT} safe codes, found {len(safe_codes)}; "
            "review enum drift and update the expected count intentionally"
        )
    expected = build_output(mapping, safe_codes)

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"FAIL: {OUTPUT_PATH} does not exist", file=sys.stderr)
            sys.exit(1)
        committed = OUTPUT_PATH.read_text(encoding="utf-8")
        if committed == expected:
            print(
                f"OK: {OUTPUT_PATH} is up to date "
                f"({len(mapping)} messages, {len(safe_codes)} safe codes)"
            )
        else:
            print(
                f"FAIL: {OUTPUT_PATH} is out of date. "
                f"Run 'python scripts/generate-error-enums.py' to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
    else:
        OUTPUT_PATH.write_text(expected, encoding="utf-8")
        print(
            f"Wrote {OUTPUT_PATH} "
            f"({len(mapping)} messages, {len(safe_codes)} safe codes)"
        )


if __name__ == "__main__":
    main()
