name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  merge_group:

jobs:
  pre-commit:
    name: Pre-commit
    uses: ./.github/workflows/reflow-pre-commit.yml

  rust:
    name: Rust
    uses: ./.github/workflows/reflow-rust.yml

  coverage:
    name: Coverage
    uses: ./.github/workflows/reflow-coverage.yml

  all:
    name: all
    if: always()
    needs: [pre-commit, rust, coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
