name: Mise

on:
  workflow_call:

jobs:
  check:
    name: Lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4
        with:
          install_args: --locked --dry-run
          cache: false
        env:
          RUSTUP_TOOLCHAIN: stable
