name: Pre-commit

on:
  workflow_call:

jobs:
  library:
    name: Generate library
    uses: ./.github/workflows/reflow-library.yml

  check:
    name: 🔶 ${{ matrix.os.emoji }} ${{ matrix.arch.emoji }} ${{ matrix.os.name }} ${{ matrix.arch.name }}
    needs: library
    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.library.outputs.matrix).axes.os }}
        arch: ${{ fromJSON(needs.library.outputs.matrix).axes.arch }}
        exclude: ${{ fromJSON(needs.library.outputs.matrix).exclude.windows-arm }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
        env:
          RUSTUP_TOOLCHAIN: stable

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.pre-commit-config.yaml', 'mise.toml', 'mise.lock') }}

      - run: pre-commit run --show-diff-on-failure --color=always --all-files
