name: Coverage

on:
  workflow_call:

jobs:
  library:
    name: Generate library
    uses: ./.github/workflows/reflow-library.yml

  check:
    name: ☂️ ${{ matrix.os.emoji }} ${{ matrix.arch.emoji }} ${{ matrix.os.name }} ${{ matrix.arch.name }}
    needs: library
    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.library.outputs.matrix).axes.os }}
        arch: ${{ fromJSON(needs.library.outputs.matrix).axes.arch }}
        exclude: ${{ fromJSON(needs.library.outputs.matrix).exclude.windows-arm }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
        env:
          RUSTUP_TOOLCHAIN: stable

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Generate coverage
        run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          use_oidc: true
          files: lcov.info
          flags: rust
          fail_ci_if_error: true
