name: Library

on:
  workflow_call:
    outputs:
      matrix:
        description: Matrix configuration as JSON
        value: ${{ jobs.generate.outputs.matrix }}

jobs:
  generate:
    name: Generate library
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.library.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Load library
        id: library
        uses: ./.github/actions/library
